version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: &dbpassword mydbpassword
    volumes:
      - mysql:/var/lib/mysql
  gem:
    build: .
    volumes:
      - .:/work
      - bundle_install:/usr/local/bundle
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - db

volumes:
  mysql:
    driver: local
  bundle_install:
    driver: local
