version: '3'
services:
  gem:
    build: .
    volumes:
      - .:/work
      - bundle_install:/usr/local/bundle
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
volumes:
  bundle_install:
    driver: local
